[build-system]
    build-backend = "setuptools.build_meta"
    requires = [
        "setuptools>=47",
        "wheel>=0.34",
        "cython>=0.29.24; python_implementation == 'CPython'", # Skip cython when using pypy
    ]

[tool.black]
line-length = 79
target-version = ['py37']


[tool.pytest.ini_options]
addopts = "--tb native -v -r sfxX --maxfail=250 -p warnings -p logging"
python_files = "test/*test_*.py"
minversion = "6.2"
filterwarnings = [
    "ignore::sqlalchemy.exc.SAPendingDeprecationWarning",
    "error::sqlalchemy.exc.SADeprecationWarning",
    "error::sqlalchemy.exc.SAWarning",
    "always::sqlalchemy.exc.SATestSuiteWarning",
    "error::DeprecationWarning:test",
    "error::DeprecationWarning:sqlalchemy"
]
